### ISSUE TITLE
can't set TXtail = 10

### ISSUE THREAD

**Issue by jh4xsy** [pfiliberti/tncemu#2]
I want to set TXtail = 10, But I can't set  my KISS TNC.

```
$ ./tnc -t 192.168.0.75 -k
Connecting with Target Host 192.168.0.75 at port 10093
Protocol: KISS
Starting Emulation "hk21rom.bin"...
```
I use [direwolf](https://github.com/wb2osz/direwolf) as KISS TNC.  TNC was set to TXTAIL=0.
```
Dire Wolf version 1.7
Includes optional support for:  hamlib cm108-ptt

Reading config file /home/jh4xsy/direwolf.conf
(snip)
Attached to KISS TCP client application 0 on port 10093 ...

Ready to accept KISS TCP client application 1 on port 10093 ...
KISS protocol set Persistence = 63, chan 0
KISS protocol set TXDELAY = 30 (*10mS units = 300 mS), chan 0
KISS protocol set SlotTime = 10 (*10mS units = 100 mS), chan 0
KISS protocol set TXtail = 0 (*10mS units = 0 mS), chan 0 ★
Setting TXTAIL so low is asking for trouble.  You probably don't want to do this.
See "Radio Channel - Transmit Timing" section of User Guide for explanation.
```
But there is NO TXtail! command.
```
cmd:disp ti
ABAUD    38400
AXDELAY  10
AXHANG   0
CHECK    30
CLKADJ   8
CMDTIME  1
CPACTIME OFF
DWAIT    0
FRACK    3
HBAUD    1200
PACTIME  AFTER 10
PERSIST  63
PPERSIST ON
RESPTIME 0
SLOTTIME 10
TXDELAY  30
```

**Comment by pfiliberti** [comment]
In the tnc set setting AXHANG. When in Kiss Mode this setting is sent to Kiss Device as txtail. Sorry it is only documented in the doc/Emulation.txt file. I will make better instructions for Kiss mode. Arigato Gozaimasu

**Comment by jh4xsy** [comment]
Thanks @pfiliberti san. I was able to set TXtail=10 using AXHANG.

**Comment by pfiliberti** [comment]
Dear Iwamotosan,

I was wondering if you knew that Heathkit HK-21 Pocket Packet was basically
a TASCO u21.
I have eprom image for U21 and I think it will run in TNCEMU. I was
wondering if you have a manual
for Tasco u21 because there is a command in the command set KNJ ON/OFF. I
am wondering if that
turn on some kind of Kanji encoding/decoding or what it does.

Thanks again for looking at TNCEMU

Peter

**Comment by jh4xsy** [comment]
Hi again.

I used to use TASCO TNCs with KNJ command, but  I sold them with manual.
So from my memory, when KNJ is ON, error messages are displayed in Japanese (Shift-JIS code).

**Comment by pfiliberti** [comment]
Wagata. Arigato gozaimasu.
